import type { Metadata } from "next";
import "./globals.css";
import Footer from "./_components/Footer/Footer";
import Navbar from "./_components/NavBar/NavBar";
import Sidebar from "./_components/SideBar/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Sidebar />
        <div className="flex mt-14">
          <div className="hidden w-14 flex-none md:block"></div>
          <div className="flex-1">{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
